### ISSUE TITLE
undfined method `configure' for Mjml:Module

### ISSUE THREAD

**Issue by KittyGiraudel** [MQuy/mjml#1]
Hi,

We are trying to use your gem in our application at Edenspiekermann, but we end up with a weird error:

```
/Users/hgiraudel/Sites/amaphiko-api/config/application.rb:50:in `<class:Application>': undefined method `configure' for Mjml:Module (NoMethodError)
    from /Users/hgiraudel/Sites/amaphiko-api/config/application.rb:10:in `<module:Amaphiko>'
    from /Users/hgiraudel/Sites/amaphiko-api/config/application.rb:9:in `<top (required)>'
    from /Users/hgiraudel/.rvm/gems/ruby-2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
    from /Users/hgiraudel/.rvm/gems/ruby-2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
    from /Users/hgiraudel/.rvm/gems/ruby-2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Users/hgiraudel/.rvm/gems/ruby-2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /Users/hgiraudel/.rvm/gems/ruby-2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/hgiraudel/.rvm/gems/ruby-2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Any idea what could cause this? If we skip the configuration part, we end up with the same problem with the `render` method in our mailer. We run on Ruby 2.2.0 and Rails 4.2.6. 

Thanks.

**Comment by MQuy** [comment]
@HugoGiraudel ops, my bad. I use the default from node_modules, therefore, i don't meet the problem.
Fixed it now, could you use version 0.0.2?

**Comment by KittyGiraudel** [comment]
Hey, better but still not! Seems like a problem with some caching…?

![Screenshot](http://i.imgur.com/njh9AEL.png)

Here is what we did:

``` sh
# ./Gemfile
gem 'mjml', '~> 0.0.2'
```

``` ruby
# ./app/mailers/foobar_mailer.rb
class FoobarMailer < ActionMailer::Base
  def baz
    body = Mjml.render("#{Dir.pwd}/app/views/foobar_mailer/baz.mjml", {})
    mail(to: 'test@example.com', subject: 'test', body: body)
  end
end
```

``` erb
# ./app/views/foobar_mailer/baz.mjml
<% name = 'bar' %>
<mjml>
  <mj-body>
    <mj-container>
      <mj-text>Hello <%= name %></mj-text>
    </mj-container>
  </mj-body>
</mjml>
```

``` ruby
# ./app/spec/mailers/previews/foobar_mailer_preview.rb
class FoobarMailerPreview < ActionMailer::Preview
  def baz
    FoobarMailer.baz
  end
end
```

``` ruby
# ./config/routes.rb
if Rails.env.development?
    get '/rails/mailers'       => "rails/mailers#index"
    get '/rails/mailers/*path' => "rails/mailers#preview"
end
```

``` ruby
# ./config/application.rb
Mjml.configure do |config|
  config.exec_path = `which mjml`
end
```

**Comment by MQuy** [comment]
@HugoGiraudel Could you try replacing `Mjml.render("#{Dir.pwd}/app/views/foobar_mailer/baz.mjml", {})` into `Mjml.render("#{Dir.pwd}/app/views/foobar_mailer/baz", {})`

**Comment by KittyGiraudel** [comment]
```
No such file or directory @ rb_sysopen - /Users/hgiraudel/Sites/amaphiko-api/app/views/foobar_mailer/baz
```

**Comment by MQuy** [comment]
Sorry, this is correct `Mjml.render("#{Dir.pwd}/app/views/foobar_mailer/baz.mjml", {})`, quite strange
Do you have folder `tmp`

**Comment by KittyGiraudel** [comment]
Yep I do:

![Screenshot](http://i.imgur.com/HzUmhs4.png)

All `template-*` files contain the same thing, what you see on the right panel.

**Comment by MQuy** [comment]
do you install mjml? quite strange 💭 
`npm install -g mjml`

**Comment by KittyGiraudel** [comment]
I did.

**Comment by KittyGiraudel** [comment]
Every time I try to compile, a new template file is being added to `tmp`, but not the one that is being requested.

**Comment by MQuy** [comment]
yup, it happens due to can not run the `mjml` to compile `.mjml` into `.html`
does it work in your local? `mjml -r input.mjml -o output.html`

**Comment by KittyGiraudel** [comment]
Yes.

**Comment by MQuy** [comment]
Can you try with this solution add package.json into your rails project and content

``` json
{
  "name": "xxx",
  "version": "0.0.1",
  "dependencies": {
    "mjml": "latest"
  },
  "engine": {
    "node": "6.1.x",
    "npm": "3.8.x"
  }
}
```

And remove the configure to use default config, I use this approach at my machine

**Comment by KittyGiraudel** [comment]
Ah. Changed a bit.

```
undefined local variable or method `body' for #<FoobarMailer:0x007ff9177836c0>
```

``` ruby
class FoobarMailer < ActionMailer::Base
  default from: 'noreply@example.com'

  body = Mjml.render("#{Dir.pwd}/app/views/foobar_mailer/baz.mjml", {})

  def baz
    mail(to: 'test@example.com', subject: 'test', body: body)
  end
end
```

**Comment by MQuy** [comment]
Founded it, fixed it now, can you use `0.0.3`

**Comment by KittyGiraudel** [comment]
Same error.

**Comment by MQuy** [comment]
can you restart server again? it worked on my local with `which mjml`

**Comment by KittyGiraudel** [comment]
Nope, did not help. :(

**Comment by KittyGiraudel** [comment]
Wait.

**Comment by KittyGiraudel** [comment]
Much better. :)

**Comment by MQuy** [comment]
does it work?

**Comment by KittyGiraudel** [comment]
It seems so. I have another minor issue but it doesn’t seem related to your gem. Thank you!

**Comment by MQuy** [comment]
you're welcome, thank so much for the issue 😄

**Comment by MQuy** [comment]
one more thing you can `<%= render 'xxxx', formats: [:mjml] %>` in your partials with this add into mime types `Mime::Type.register_alias "text/plain", :mjml`

**Comment by KittyGiraudel** [comment]
This does not seem to work though. :(

``` ruby
# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf
Mime::Type.register_alias "text/plain", :mjml
```

``` erb
<%= render 'qux', formats: [:mjml] %>
```

It seems to break the compilation: 

```
undefined method `render' for #<Mjml::Render:0x007fe1a7674798>
```

**Comment by MQuy** [comment]
can you change into this `<%= render partial: 'qux', formats: [:mjml] %>` and this line is in mjml partials, right?

**Comment by KittyGiraudel** [comment]
> and this line is in mjml partials, right?

Not sure what you mean. :x
This line is in my mjml template yes.

**Comment by MQuy** [comment]
In your `abc.mjml`, you can do that

``` html
<%= render partial: 'xxxx', formats: [:mjml] %>
```

**Comment by KittyGiraudel** [comment]
Yep. It’s the case. Doesn’t work. :(

**Comment by KittyGiraudel** [comment]
The `render` method doesn’t seem to be recognized.

**Comment by MQuy** [comment]
it works well on my local, so strange. Do you have a sample?

**Comment by MQuy** [comment]
do you use version 0.0.5?

**Comment by KittyGiraudel** [comment]
I will give it another try soon. I was using 0.0.3. :)

**Comment by MQuy** [comment]
haha, you are so quick, to make it work on version 0.0.5. In your mailer, you should do like this
`Mjml.render("#{Dir.pwd}/app/views/foobar_mailer/baz.mjml", {}, self)`
it allows you to use route helper in template also
